### ISSUE TITLE
Error when building worker image

### ISSUE THREAD

**Issue by rsirel** [EMBEDDIA/ULR_NER_REST#1]
Got an error when building worker image:
```
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-libc-dev_4.19.67-2+deb10u1_amd64.deb  404  Not Found [IP: 151.101.64.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Solution:
Replace this line: https://github.com/EMBEDDIA/ULR_NER_REST/blob/master/services/celery-queue/Dockerfile#L27
with:
```
apt-get update && apt-get -y install g++ unzip && \
```

**Comment by creat89** [comment]
I have updated the code and it shoudl fix the issue. Reopen the issue if you have another one.
